### ISSUE TITLE
Add new workflow to generate Release note and version tag automatically

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/android-templates#100]
## Why

The template needs to be released every month so adding a new workflow to handle release notes and version tag on every new releases

## Who Benefits?

Android chapter

**Comment by sleepylee** [comment]
how was this going, @hoangnguyen92dn @lydiasama ?

**Comment by hoangnguyen92dn** [comment]
@sleepylee Noone started working on this issue yet. I think this is a good chance for @doannimble to getting familiar with our CI/CD setup.

**Comment by sleepylee** [comment]
I think if we decide to work on this, perhaps you should get the approval from the chapter lead first. Making sure that they understood and agree with your suggestion before starting the assignment, which also requires volunteerism

**Comment by lydiasama** [comment]
@hoangnguyen92dn Can it use the release template that we already have? I do it manually picking the issue number into the note these days.

**Comment by hoangnguyen92dn** [comment]
@lydiasama For now, we have to create manually on every release. Therefore, the initial idea is to create `release` and `tag` automatically once the release PR merges to `main`.

**Comment by sleepylee** [comment]
@hoangnguyen92dn oh so it's about the release automation. From your title: `archive Release note and version tag automatically` - it was a bit confusing tbh. I was not sure why would we have to archive the note 🤔  

archive (verb) place or store (something) in an archive.
/ˈärˌkīv/

maybe name it as `generate release note and tagging automatically`? 🤔

**Comment by hoangnguyen92dn** [comment]
@sleepylee 
> maybe name it as generate release note and tagging automatically? 🤔

👍  

Updated 😄

**Comment by Tuubz** [comment]
@AVI5HEK Any update on this one? 🚀
