### ISSUE TITLE
Create a Github template for the release PRs

### ISSUE THREAD

**Issue by longnd** [nimblehq/android-templates#112]
## Why

We already have the [pull request template](https://github.com/nimblehq/android-templates/blob/main/.github/PULL_REQUEST_TEMPLATE.md) in the Android template. But that template isn't applicable for the releases. As a result, the release PRs format can be inconsistent between every project. 
As we now have the [convention](https://nimblehq.co/compass/development/version-control/release-management/#release-pull-request) for the release PR, it should be reflected in this template.

## Who Benefits?

Android chapter

**Comment by sleepylee** [comment]
I think you could then close this PR? @lydiasama or was it done tho?

**Comment by lydiasama** [comment]
@sleepylee Sure, I will. I'm just not sure I can close it. 🙆🏻‍♀️
