### ISSUE TITLE
Add Proxyman configurations to intercept requests/responses

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#117]
## Why

[Proxyman](https://docs.proxyman.io/) is a tool that acts as proxy, to intercept requests and responses between the client and server. By doing this we can gain control over the traffic that's being sent and received in our app. 

We need to add a network security config file to whitelist the domains that we will be intercepting (only for staging env)

## Who Benefits?

@nimblehq/android-chapter can view, inspect and manipulate the content of requests and response for testing 🚀

**Comment by lydiasama** [comment]
@Tuubz We need to disable the pinning certification as well, Does it include inside of this content?

**Comment by Tuubz** [comment]
@lydiasama Could you please refresh my memory why we need to disable the pinning certificate? 🙇 

Anyhow, I don't think it relates directly to this ticket 🙏

**Comment by lydiasama** [comment]
@Tuubz As I use the proxyman with DeeMoney project. only adding the network security config is not enough. We need to disable the pinning certificate as well. Have you tried the proxyman with the pinning certificated projects? If it works, I maybe need your help. 🙏🏻

**Comment by Tuubz** [comment]
@lydiasama Aah, I see

No, it wasn't required for the 7-Eleven project. 

Also, for this project it's not required too. So I'm not sure if we should add it here

What did you do to solve it on DeeMoney project? 🙏

**Comment by lydiasama** [comment]
@Tuubz I just create my local branch to add those configurations. I'm thinking to bring it into the new buildType `mock` as well for convenience.

**Comment by Tuubz** [comment]
Continue discussion in [this thread](https://nimble-co.slack.com/archives/G41UCTGHL/p1629781993001700)
