### ISSUE TITLE
Update Github Action workflows follow Github Action team convention

### ISSUE THREAD

**Issue by lydiasama** [nimblehq/android-templates#124]
## Why

Our current Github Action workflows code style doesn't follow the [team convention](https://nimblehq.co/compass/development/code-conventions/github-actions/). So we need to update.

Here is the list of what we already follow and what we need to follow according to the convention
- ❌  Add a line break between each root-level block
- ✅  Add a line break between each job step
- ❌  Refactor workflows naming (should start with a verb)
- ❌  The name attribute for the job must be provided (some still missing)
- ❌  The name attribute jobs set must be provided and follow the pattern “Verb description”
- ✅  Command syntax, both single line (should be on the same line), and multiple lines (using `|`)
- ❌  Prefer to set a timeout for each job (currently there’s no job with a defined timeout)

<img width="809" alt="Screenshot 2021-11-02 at 12 51 35" src="https://user-images.githubusercontent.com/12026942/139803221-bc1b862e-d2b9-4a91-b23f-072464d33d2d.png">

<img width="260" alt="Screenshot 2021-11-02 at 12 56 12" src="https://user-images.githubusercontent.com/12026942/139803258-712da20c-0038-4649-b34e-605fc13ce36f.png">

<img width="356" alt="Screenshot 2021-11-02 at 12 59 43" src="https://user-images.githubusercontent.com/12026942/139803287-7fdb7e99-f8a8-415d-9d94-0ebc22632f8b.png">

<img width="482" alt="Screenshot 2021-11-02 at 13 01 14" src="https://user-images.githubusercontent.com/12026942/139803328-6260e76e-9465-45ee-b605-d9513448ecee.png">

## Who Benefits?

@nimblehq/android-chapter

**Comment by sleepylee** [comment]
I thought we had already followed 🤔  perhaps you might want to point out some examples so that others can take care of the issue, @lydiasama

**Comment by chornerman** [comment]
> I thought we had already followed 🤔 perhaps you might want to point out some examples so that others can take care of the issue, @lydiasama

@sleepylee @lydiasama Updated 👍🏼
