### ISSUE TITLE
Add RFC template for usage

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/android-templates#146]
## Why

Following the Compass repository, there is a template for creating the RFC when the issue needs to be voted for agreement by the team. Android repository is lacking this template.

## Who Benefits?

Developers

**Comment by hoangnguyen92dn** [comment]
@lydiasama Please review this issue then I would open PR to resolve 🙏

**Comment by luongvo** [comment]
👍

**Comment by lydiasama** [comment]
@hoangnguyen92dn Approved. ✅  Sorry for my late. 😭

**Comment by sleepylee** [comment]
#150
