### ISSUE TITLE
Support DataStore in a replacement for SharedPreference

### ISSUE THREAD

**Issue by sleepylee** [nimblehq/android-templates#159]
## Why

As recommended by Google, it is more efficient and practical to use DataStore instead of SharedPreference. Perhaps it is time for us to consider having this either as a mandatory or an option to initialize a project.

Read more:
- https://android-developers.googleblog.com/2020/09/prefer-storing-data-with-jetpack.html

- https://developer.android.com/topic/libraries/architecture/datastore

## Who Benefits?

Template users.

👍 : make it a default choice of storage
👎  : make it an optional choice after SharedPreference.

**Comment by lydiasama** [comment]
@sleepylee Do we need another RFC about saving the preference synchronously or asynchronously?

**Comment by sleepylee** [comment]
@lydiasama I think it is depending on the use-case of a project and we can improvise later. If you look at the comparison chart, by default, DataStore provides async API - but if I'm not wrong, you can always `await` for an async call to reply instead of making a synchronous call.

![image](https://user-images.githubusercontent.com/13435717/154405244-0eebfff4-81be-4c46-be35-3429d9078f12.png)

**Comment by Tuubz** [comment]
Anyone interested in taking responsibility for this ticket? Currently we're using `NormalSharedPreferences.kt`, `EncryptedSharedPreferences.kt` & `BaseSharedPreferences.kt`, so we'll have to make some changes in those classes. 

`v3.7.0 - Release date: 30/04/22`

Respect points guaranteed: 

![2771433-5751838547-10692](https://user-images.githubusercontent.com/18277915/159403059-c876d099-3f34-4283-996d-7ee65b81e15c.jpeg)

**Comment by lydiasama** [comment]
@Tuubz Let me try this one. 😁

**Comment by Tuubz** [comment]
@lydiasama Yes, please do 🤩 🤩 🤩

**Comment by Tuubz** [comment]
@lydiasama I think we will have to postpone adding new features, until after we finish [separating sample code into separate folder](https://github.com/nimblehq/android-templates/issues/193). Otherwise, there could be some conflicts, what do you think? 🙏

**Comment by lydiasama** [comment]
@Tuubz Sorry for the late reply. It's okay. 🙏

**Comment by luongvo** [comment]
@ryan-conway @lydiasama This issue should not be closed yet 👀
