### ISSUE TITLE
Update Gradle to version 7+ 

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#163]
## Why

Change the Gradle version as following:
- Android Gradle Plugin version: `4.2.1` > `7.1.2` or higher
- Gradle version: `6.7.1` > `7.4.1` or higher

## Who Benefits?

Developers will benefit from faster building times and more: https://gradle.org/whats-new/gradle-7/

I think this is **essential**, as it will bring a good experiences for the developers themselves

**Comment by sleepylee** [comment]
@Tuubz will there be any conflict or restriction with the android build tools, or Android studio version, java/kotlin version with this upgrade?

**Comment by Tuubz** [comment]
@sleepylee I've quickly tried upgrading the Gradle version as mentioned in the pull request description.

I can build app successfully after making the following changes:

- Remove `versionCode` & `versionName` from `build.gradle.kts (:data:)` > [Read more](https://stackoverflow.com/questions/67803478/error-unresolved-reference-versioncode-in-build-gradle-kts)
- Upgrading to Java v11 is required > Most of us are still using Java v1.8 if I'm not mistaken

What do you think? 🙏

**Comment by manh-t** [comment]
@Tuubz upgrading to Java 11 may cause the build to fail if we use a 3rd-party lib that is using Java 1.8 ([Jacoco for example](https://github.com/nimblehq/android-templates/pull/137/files#diff-6055d9b70d081d3d5d5e04ed372749f3663844b75ff1d9f91dd98a4e81a23508R115)), so we may need to recheck a bit, overall it's good 👍

**Comment by Tuubz** [comment]
@manh-t Good thinking, I'll approve it for now but won't assign this to any sprint yet (until we finish #169) 👍

**Comment by luongvo** [comment]
@Tuubz @hoangnguyen92dn We should consider upgrading Kotlin and Kotlin coroutines test versions in this task (or a separate task) as well.

![image](https://user-images.githubusercontent.com/16315358/163355510-ed76d0ef-15b5-4ccf-8754-d1156d9ceb68.png)

**Comment by hoangnguyen92dn** [comment]
@luongvo 👌 Sounds good to me 👍
