### ISSUE TITLE
Add Jacoco to CoroutineTemplate

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#169]
## Why

Jacoco is currently not supported for CoroutineTemplate, however it is working correctly for RxJavaTemplate

In `.github/workflows/review_pull_request.yml` there's a pending TODO

Let's make sure Jacoco can run the tests and generate a report in the CI successfully.

## Who Benefits?

Developers benefit by having more trustable code and can avoid boilerplate set-up for Jacoco in future projects

I think this is **essential**, because it helps with maintaining code quality

**Comment by luongvo** [comment]
@Tuubz Let me take care of this one too 👯‍♂️

**Comment by Tuubz** [comment]
@luongvo 🤩 🤩🤩

**Comment by hoangnguyen92dn** [comment]
@luongvo Okie...First come first serve 🤣 
![image](https://user-images.githubusercontent.com/6950766/160749022-96035c39-cf91-4172-a389-3b5bcfcafb75.png)
