### ISSUE TITLE
Remove `checkStyle` 

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#171]
## Why

We can remove [checkStyle](https://github.com/checkstyle/checkstyle) because it can only be used for Java and has been replaced completely by [detekt](https://github.com/detekt/detekt). 

So let's remove anything related to `checkStyle` accordingly 🎸 

## Who Benefits?

Developers will have a cleaner codebase with less chance for confusion

I think this is **essential**, because it helps with maintaining code quality

**Comment by luongvo** [comment]
@Tuubz This one is optional imo since it's integrated without no issues, removing it will take our effort.

**Comment by Tuubz** [comment]
@luongvo Hmmm, if I'm not mistaken we're not using it anymore (we don't have any Java classes left in our code)

Wouldn't you say it would be essential to have it removed (to avoid confusion and to maintain clean code) 🙏 

If we decide it to be optional, it would mean that we could add a flag to our script to include `checkStyle` 🤔

**Comment by luongvo** [comment]
> If we decide it to be optional, it would mean that we could add a flag to our script to include checkStyle 🤔

@Tuubz Hmm, I forgot this point, so I agree to set this task to be `essential`, we should remove `checkStyle` but it's not in rush.
