### ISSUE TITLE
Add debug keystore config for CI to CoroutineTemplate

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#184]
## Why

We're missing a setup for debug keystore for the Coroutine template which has been mentioned here  https://nimblehq.co/compass/development/android/project-configurations/#keystore-for-cicd.

## Who Benefits?

Developers, PM and Testers

I think this is **essential** because it's documented action on Compass already to avoid annoying app uninstalling required for testers, PM to test new app release.

**Comment by Tuubz** [comment]
@luongvo Hmmmm, it's nice that we already created a pull request for it: #186 

But I think that all newly created **features** and **chores** should go through the voting process first (a.k.a `need voting`)

What do you think?

**Comment by luongvo** [comment]
@Tuubz yes, please help me to add this ticket into our voting process 👌 I believe it should be a MUST, just not sure about the milestone

**Comment by Tuubz** [comment]
@luongvo Bro, you can't upvote your own issue 😂

**Comment by Tuubz** [comment]
@luongvo Also, please specify in ticket description why you think it's essential 🙇

**Comment by luongvo** [comment]
@Tuubz added reason to be a essential ticket.

**Comment by Tuubz** [comment]
Aha, I see

So we already had it for `release`, but not yet for `debug` 👍

**Comment by Tuubz** [comment]
@luongvo Since #186 already has enough approvals, I'll set this issue as `approved : essential` 🚀
