### ISSUE TITLE
Avoid defining app credentials via BuildConfig

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#188]
## Issue

Currently, we're having a sample to define [BASE_API_URL](https://github.com/nimblehq/android-templates/blob/develop/CoroutineTemplate/app/build.gradle.kts#L41) via `BuildConfig`. **BuildConfig will not be obfuscated by proguard** so this way is not safe to go, especially when we have more secrets like `API_KEY` or `API_SECRET`. We should provide them through a separate class which will be obfuscated in each `flavor` folder instead.

## Solution

By having 2 environments as default: `production` and `staging`, we will need to define 2 new `ApiEndpointUrl` classes in each flavor.

![image](https://user-images.githubusercontent.com/16315358/163514486-2fe2bf1d-924a-4571-8fec-335ed0ec298b.png)

## Who Benefits?

Developers

I think this is **essential** because app credentials management is very important.

## What's Next?

- [ ] Remove [BASE_API_URL](https://github.com/nimblehq/android-templates/blob/develop/CoroutineTemplate/app/build.gradle.kts#L41) definition via `BuildConfig`
- [ ] Define 2 new `ApiEndpointUrl` classes in each flavor to provide API endpoint urls.

**Comment by luongvo** [comment]
@Tuubz added reason to be **essential** ticket

**Comment by sleepylee** [comment]
@luongvo you might want to have a quick check again, simply read a field from BuildConfig, package an APK and then run jadx to reverse it. It seems like if we are not defining 

`-keep class com.example.BuildConfig { *; }` in proguard file, it will be obfuscated like this: 
 
![image](https://user-images.githubusercontent.com/13435717/165228698-75f0c617-250d-4756-91c8-d2cc254b6c89.png)

Seems like it works nicely these days with proguard/R8. If so, we should continue to keep this practice.

**Comment by sleepylee** [comment]
or maybe it worked with the conversion from gradle.properties -> gradle.app -> BuildConfig -> app 

https://medium.com/@abhishekdubey_70837/using-gradle-to-secure-app-keys-in-android-9d2796ca4007

the expected outcome is that the plain string must not be visible, either using the class way or this way 🆗

**Comment by sleepylee** [comment]
with the class obfuscation, only the var name is obfuscated FYI 
![Screen Shot 2022-04-26 at 13 00 07](https://user-images.githubusercontent.com/13435717/165232076-2fbeb567-a043-493b-b23f-9ab767832e58.png)

**Comment by manh-t** [comment]
@luongvo I have checked by decompiling the APK and the result is the same with @sleepylee . 🙏 

- Here is the `apiEndpointUrl` from the new approach
![image](https://user-images.githubusercontent.com/60863885/165472256-3fdcee7e-a7e2-4852-8467-82897243cfc6.png)

- And this is from `BuildConfig`
![image](https://user-images.githubusercontent.com/60863885/165475658-846f3d34-f9c0-4b4d-95d7-e9df75874817.png)

The classes/ method is obfuscated only, not the value 😅

**Comment by sleepylee** [comment]
@manh-t it's public repository so we better not leaking client's detail.

**Comment by Tuubz** [comment]
I can confirm that both `BuildConfig` & `ApiEndpointUrl ` only obfuscate the function name and _not_ the value itself 🙏  

<img width="1436" alt="Screen Shot 2565-04-29 at 11 22 27" src="https://user-images.githubusercontent.com/18277915/165885049-77370e84-21f2-4c82-b9ae-6b1ce3b815cd.png">

However, I do have a preference for `ApiEndpointUrl` (Ex: `Secrets.kt`):
   - Cleaner code separation
   - No need to Gradle sync after making an update
   
@luongvo Any thoughts? In case you agree, would you mind rewriting the description of this issue? 🚀

**Comment by sleepylee** [comment]
@Tuubz did you try the solution I provided above? It seems that I and @manh-t receive a new result here with BuildConfig: both the name + value are obfuscated ⭐

**Comment by Tuubz** [comment]
@sleepylee Oh, seems like I misunderstood then

Anyways, I tried the following for CoroutineTemplate:

1. Enable `isMinifyEnabled` & `isShrinkResources` to `true`
2. Move `BASE_API_URL` in to `gradle.properties`
3. Adapt `build.gradle.kts` so `BASE_API_URL` is used: `buildConfigField("String", "BASE_API_URL", baseApiUrl)`
4. Generate an APK
5. Run `jadx` on the APK
6. Open up the result in a text-editor
7. Search references for `BASE_API_URL`

Did I miss something here? 🙇

**Comment by sleepylee** [comment]
@Tuubz that sounds correct and the value URL is supposed to be obfuscated as well with this approach 🤔  Not sure what could be missing from your side, so could you please zip the codebase (remove your build/ part to minimize the size) and post it here for us to investigate?

**Comment by Tuubz** [comment]
@sleepylee @manh-t I tried this on `CoroutineTemplate` could you guys do the same? 🙏 

If the value is still obfuscated on your side, then something is definitely missing in the code. 

Or perhaps something is wrong with my `jadx`, when I run it says: `finished with errors, count: 27` 🙈

**Comment by manh-t** [comment]
@sleepylee unfortunately, Toby and I got the same result 💸  Although I didn't keep `BuildConfig` in `proguard`, it doesn't obfuscate the `BuildConfig`'s value as the image I provided above.
I'm using Worpt project for demonstration 🙏  Not sure if there is any extra config from your side, we'd love to know that 🙏 

> * And this is from `BuildConfig`
>   ![Screen Shot 2022-04-27 at 15 31 53](https://user-images.githubusercontent.com/60863885/165476880-58cd9c4e-2ecd-4325-b4a0-3d7d508ebfc6.png)

**Comment by Tuubz** [comment]
Continue discussion [here](https://nimble-co.slack.com/archives/G41UCTGHL/p1651212032946899) 👋

**Comment by Tuubz** [comment]
@luongvo Our plan is to go with the `BuildConfig + properties` approach instead, what do you think? 

If you agree, I can create a new issue and reject this one

**Comment by luongvo** [comment]
This issue is now invalid and should be closed
