### ISSUE TITLE
Update Jacoco for release flavor

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#192]
## Why

Currently, Jacoco is only executable for `debug` flavor, but we should have support for `release` flavor too.

Benefits:
- Possibility to write tests that have conditions regarding `BuildConfig.RELEASE` 
- Ensure nothing went wrong during obfuscation (pro-guard)

Reference: [StackOverflow](https://stackoverflow.com/questions/44740966/testing-android-app-release-build-variant)

Please also refer to [this thread](https://nimble-co.slack.com/archives/G41UCTGHL/p1650279207853519) for extra details:

## Who Benefits?

Developers will benefit from broader testing and more reliable code

I think this is essential, as it will maintain the code quality

**Comment by Tuubz** [comment]
@AVI5HEK Does it mean you agree that this should be **essential**, because Lucas disagrees

Would be nice to get your input here too 🙇

**Comment by sleepylee** [comment]
if it targets to run on every commit I think it will pressure on the build & validating time with the obfuscation + gen report. I think we can do it on a merge that should be good.

**Comment by Tuubz** [comment]
@luongvo @hoangnguyen92dn 

Please keep in mind that 👎 might indicate you want it "**rejected**", but that's not the case, right? 😁 

Seems to me that this will eventually be "**approved**", the question is whether it will be "**essential**" or "**optional**"

You can put a 👎 on my comment instead 😄

**Comment by hoangnguyen92dn** [comment]
@Tuubz As Trung mentioned about the cost when executing on release flavor, I don't think we need to execute Jacoco on release build even  "essential" or "optional" 😄

**Comment by Tuubz** [comment]
@sleepylee Could you please specify what your stance is on this? (Essential, optional or rejected) 🙏

**Comment by sleepylee** [comment]
imo, the goal with Jacoco is to see how well our source code is being tested thoroughly. It doesn't necessarily have to cover anything further than that. On a Release build there is code shrinking and obfuscation process, they are irrelevant to the actual code we wrote, so why do we need to spend time and resource on it? 🤔 If we need to run gradlew test; the goal is to test on all flavors and that makes sense, but I don't see a mandatory force to get the coverage report from it. So I would conclude with a Rejected eventually.

**Comment by Tuubz** [comment]
I considered this essential so we can support release-specific tests (Ex: Verify Crashlytics is only enabled for production), but I suppose they are very minor and actually not so common to have at all.

So let's reject this issue 🚀
