### ISSUE TITLE
[Sample] Create sample folder to showcase features

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#193]
## Why

The CoroutineTemplate folder consists of both **template**- and **sample** code. Because whenever we add a feature, we want to showcase it too, as proof of work. This mix-up of code is confusing and unnecessary, so we must aim for a (c)lean template, by separating the template- and sample code.

How do we differentiate between template- and sample code?
- **Template**: Anything that is essential for starting a project (You can think of how Android Studio generates a new project)
- **Sample**: Anything that gets removed eventually by the [the script](https://github.com/nimblehq/android-templates/blob/develop/newproject.sh), with its only purpose to showcase a feature

---

**Expectations**?
- Initialize a project inside a newly created `sample` folder
- Create more tickets to transfer features from `app/data/domain` into the `sample` folder (Ex: Compose)
- Create a ticket to rename `CoroutineTemplate` to `template`
- Create a ticket to adapt the code in [the script](https://github.com/nimblehq/android-templates/blob/develop/newproject.sh)

## Who Benefits?

Developers, especially new joiners, as there will be a clear separation between the template- and sample code.

I think this is **essential** as it will be a good experience for the developers themselves.

- [x] #240 
- [x] #241 
- [x] #242 
- [x] #243 
- [x] #244

**Comment by luongvo** [comment]
@Tuubz I do agree with this refactoring 👍  

Also, I just want to show my next idea is updating our template script to have an option to choose between `xml layout` or `Jetpack Compose`. Both of them are UI View binding methods so it should be initialized from the template. 🤓

**Comment by hoangnguyen92dn** [comment]
@Tuubz Just want to add one more point, should we create a list of samples and separate samples on different Activity/Fragment? 🤔  So for example: 

- SampleListActivity
  - Compose -> ComposeAcvitiy

**Comment by Tuubz** [comment]
Yes, good idea 👍 

This issue will be the `epic`, so I'll create more `stories` for this soon 🚀

**Comment by manh-t** [comment]
@Tuubz just curious, are you going to create **a sample app** with multiple sample features inside, or **multiple sample apps** with a feature per app? 🙏

**Comment by Tuubz** [comment]
@manh-t Good question 👍 

I plan to go with one sample app that contains multiple sample features inside

Please let me know if you disagree 🙏

**Comment by luongvo** [comment]
@Tuubz @manh-t @hoangnguyen92dn we can separate the samples by packages with the `SampleListActivity` at the root package 👍

**Comment by manh-t** [comment]
@Tuubz imo, I prefer `multiple sample apps` with a feature per app, like [this](https://github.com/android/compose-samples). There are scenarios where we have 2 libs with the same feature (`hilt` and `koin` for example), adding both of them into a sample app could cause confusing to the reader 😅  
If we go with `one sample app`, maybe separating into multiple modules could solve the problem? 💭

**Comment by Tuubz** [comment]
Thanks for sharing. Definitely worth considering, I'll summarize the benefits/downsides of each approach, so it will be easier to decide in group. 🚀

**Comment by hoangnguyen92dn** [comment]
@manh-t I think with the separate sample apps, it would be a showcase to build the app with a specific approach completely. IMO, the sample package in the `android-temples` should be a small piece of demonstration built based on the template instead 🤔  Please correct me if I am understand wrong the idea @Tuubz

**Comment by luongvo** [comment]
> 

@Tuubz I just added a RFC here https://github.com/nimblehq/android-templates/issues/214
