### ISSUE TITLE
Add error mapping logic to handle custom errors from data layer

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#212]
## Why

Currently, `CoroutineTemplate` does not have a logic to handle custom errors from `data` module, such as [HttpException](https://square.github.io/retrofit/2.x/retrofit/retrofit2/HttpException.html). For example, we need to know when is a validation error from API response happen to display a custom validation error on the UI 💡 .

We need to build an error mapping logic in `data` or `domain` layer to catch and pass the custom errors into the `app` module layer for other higher business implementations, instead of throwing a generic `Exception` to ViewModel.

https://github.com/nimblehq/android-templates/blob/403bd3fa68bfc2c235ff7ccef89973a38b8c341e/CoroutineTemplate/domain/src/main/java/co/nimblehq/coroutine/domain/usecase/GetUsersUseCase.kt#L9-L16

## Who Benefits?

Developers

I think this is **essential** because custom error handling is a required logic that almost apps need it.

**Comment by luongvo** [comment]
@manh-t This is a related + small task too, we will need to catch and map custom error in Repository layer 👋

**Comment by Tuubz** [comment]
@luongvo @manh-t Voted 👍 

Do you have any references for the solution? This could be useful for others to better understand the issue

**Comment by Tuubz** [comment]
@luongvo 

Please correct me if I'm wrong, the error mapping for this issue is like you explained [here](https://github.com/nimblehq/android-templates/issues/213#issuecomment-1135375842), right? `flowErrorMapping()` 🙏

**Comment by luongvo** [comment]
After discussing internally with @manh-t and @hoangnguyen92dn, I will help @manh-t to work on this ticket as it's quite related to the previous task #213 💪

**Comment by luongvo** [comment]
We need to sync this to our sample projects in part 2.
