### ISSUE TITLE
Update init script to have an option to start with either XML layout or Jetpack Compose

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#214]
## Issue

Currently the templated project is mostly based on `XML layout` and we added a sample support for `Jetpack Compose` #103. After initializing a new project, both of them are existing and confused us so it requires our effort to remove an unused one.

![image](https://user-images.githubusercontent.com/16315358/167087011-7f19db0e-f7bf-4c53-94be-590772ca81c2.png)

## Solution

We should provide an option from the template scripting level to choose to start with either `XML layout` or `Jetpack Compose`.

## Who Benefits?

Developers

I think this is **essential** because it saves our effort to clean up unnecessary config and setup when setting up a new project; also avoid confusing when having multiple UI view bindings in the same project.

## What's Next?

- [ ] Update the template init script to have an option to choose between `XML layout` or `Jetpack Compose`.
- [ ] Once the developer chose one, the script have to remove the others and add necessary configurations.
- [ ] Ensure the templated project works properly with each UI view binding method.

**Comment by ryan-conway** [comment]
@luongvo Is the goal to choose _either_ XML or Compose, or will we have an option to include both? For example,
`kscript new_project.kts package-name=com.nimble.example app-name="MyProject" --xml --compose`

**Comment by Tuubz** [comment]
@ryan-conway The goal should be to choose either XML or Compose 👍 

I don't think there's any scenario where a developer would need both 💭 

cc @luongvo

**Comment by Tuubz** [comment]
@luongvo Do you mind if I close this issue? I've created a [new issue](https://github.com/nimblehq/android-templates/issues/336), so I could specify the AC
