### ISSUE TITLE
[Sample] Create sample folder for XML

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#243]
**Description**

Create a sample project for XML inside `sample-xml`

1. Generate `sample-xml` from `new_project.kts`
2. Add sample code related to XML

**Notes**: 
- Only take the minimum which is required to showcase XML, keep it simple
- `sample-xml` must have the same folder structure as `sample-compose`

**Acceptance Criteria**
- Add sample code for XML to `sample-xml`:
   - Home screen:
       - Contains title bar at the top
       - Contains a recycler view showing API data
       - Contains a progress bar when loading API data
   - Second screen:
      - Contains title bar at the top
     - Contains information of the clicked recycler view item from home screen

- Package name must be `co.nimblehq.sample.xml`

**Comment by lydiasama** [comment]
@Tuubz What data will we show on the Home and Second screen? Currently, I found that we have only one button on the Home screen and it just navigate to the Second one when clicking.

**Comment by Tuubz** [comment]
@lydiasama That's a good question 👍 

I think we can improve the sample code in a later issue, to keep it simple.

So for now, we can just focus on separating the sample code 

What do you think? I'm open to other suggestions 😁 

cc @chornerman @nimblehq/android-chapter

**Comment by lydiasama** [comment]
So we will not focus on implementing the UI for XML version, right? @Tuubz .
Now I'm finished generating the XML project by removing all of Compose section. Will create a PR soon. 👍🏻

**Comment by Tuubz** [comment]
@lydiasama 

> So we will not focus on implementing the UI for XML version, right? @Tuubz .

We will not focus on implementing new UI, but can keep the old one 🚀 

> Now I'm finished generating the XML project by removing all of Compose section.

Sounds great! Does it mean you generated a new project based on[ these changes](https://github.com/nimblehq/android-templates/pull/253)? 🙏

**Comment by lydiasama** [comment]
@Tuubz Nope. Since the #193 doesn't mention that we should do it orderly. 😂

**Comment by Tuubz** [comment]
@lydiasama 

> Nope. Since the https://github.com/nimblehq/android-templates/issues/193 doesn't mention that we should do it orderly

Sorry for not being more clear, my plan was to do the following issues in order:

#253 > #243 > #242 

Shall we clear up #253 first, so we can agree on what to remove from the template, then we can continue with #243? 💪

 > Besides, I think we should keep the user model as the old implementation because we will need it when we implement the UI.
 
 Yup, for the sample code we keep the old implementation 🚀

**Comment by lydiasama** [comment]
@Tuubz Okay. I'll re-generate the project then.
