### ISSUE TITLE
Update Kotlin Version

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#249]
## Why

Change the Kotlin version:
- `kotlin-stdlib` : 1.5.21 > 1.7.0 or higher
- `kotlinx-coroutines-android` & `kotlinx-coroutines-test` : 1.5.0 > 1.6.3 or higher

## Who Benefits?

Developers will benefit from new features and performance improvements: 
- https://github.com/JetBrains/kotlin/releases
- https://github.com/Kotlin/kotlinx.coroutines/releases

I think this is essential, as it will bring a good experience for the developers themselves

**Comment by ryan-conway** [comment]
I agree that we should update, but we should also double check all our dependencies too. Looks like Detekt (tested with v1.20.0 and above) doesn't work properly with Kotlin 1.7.0 so Gradle syncs fail 👀 

<img width="733" alt="Screenshot 2565-07-01 at 14 48 21" src="https://user-images.githubusercontent.com/53168251/176849731-58fb90e4-69cd-47bf-8d8b-57577c288d27.png">

**Comment by luongvo** [comment]
@Tuubz are they overlapping https://github.com/nimblehq/android-templates/issues/191?

**Comment by Tuubz** [comment]
Oh, dammit. You're right. Thanks @luongvo 😂 

I'll close this issue 🙏
