### ISSUE TITLE
Add permission request handler

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#261]
## Why

[RxPermissions](https://github.com/tbruyelle/RxPermissions) is used for RxJavaTemplate. 

In our new template, we currently don't have a permissions request handler, so let's add [Peko](https://github.com/deva666/Peko) to support `Coroutine & Flow`

Reference: https://nimble-co.slack.com/archives/G41UCTGHL/p1657594027286929

## Who Benefits?

I think this is **essential** for us developers because it will bring a good experience for us.

**Comment by sleepylee** [comment]
maybe start with a prefix `[RFC]` to help improve its visibility? 💡

**Comment by Tuubz** [comment]
@sleepylee I'm glad you raised this 👍 In my opinion, adding `[RFC]` is quite redundant, because every feature or chore needs to go through a voting process anyways.

What do you think? Please correct me if I'm wrong, but I don't see any added value of the prefix 💭

**Comment by sleepylee** [comment]
it's your call, my point of view is from the backlog standpoint, as you introduced various different formats, I'm just suggesting a better way to manage their visibility better. But if you think you can manage it and so do the others, then you can skip it.
![image](https://user-images.githubusercontent.com/13435717/182080968-4589db5c-9204-4d82-804b-86ed3d36d42b.png)

**Comment by sleepylee** [comment]
and to do or to skip, please clarify so the others can follow up our conversation, just a reminder in an opposing way to an emoji, @Tuubz 😇

**Comment by Tuubz** [comment]
My bad. 

The idea for having `[xxx]` in front of the issue title was to reference the epic of that issue (for better visibility). But after discussing with Julien on [GitHub Projects Handbook](https://github.com/nimblehq/compass/issues/985), we agreed to add a new field for it in the project board instead:


![Screen Shot 2565-08-01 at 14 40 29](https://user-images.githubusercontent.com/18277915/182098095-76506901-8764-4ba9-92af-5edaaf1f05b7.png)


So I'll stop adding `[Sample]`, `[CoroutineTemplate]`, ... from now on 🙏
