### ISSUE TITLE
Update execute function for use case

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#262]
## Why

In Kotlin we can [override the invoke method](https://riptutorial.com/kotlin/example/31101/overriding-invoke-method-to-build-dsl). 

With this approach, we can eliminate `.execute()` and use the invoke function instead

---

Ex:

If we add this to our use case:
```
interface DoSomethingUseCase {
    suspend operator fun invoke(id: String)
}
```

Then we can call the use case without `.execute()`:
```
DoSomethingUseCase(id)
```

Reference: 
- https://nimble-co.slack.com/archives/G41UCTGHL/p1657876809735139
- https://github.com/nimblehq/android-templates/discussions/257

## Who Benefits?

I think this is **essential** for us developers because it will bring a good experience for us.

**Comment by ryan-conway** [comment]
Are we going to stick with the `UseCase` naming as well? Just wondering about being descriptive vs being natural to read

```kotlin
val doSomethingUseCase = DoSomethingUseCase()

fun doSomething() {
    val result = doSomethingUseCase()
}
```
vs
```kotlin
val doSomething = DoSomethingUseCase()
//val doSomething = DoSomething()

fun doSomething() {
    val result = doSomething()
}
```

**Comment by Tuubz** [comment]
My vote goes to `val doSomethingUseCase`, for a clear understanding 🤚 

In the same way, I would always include `repository` to for example `val userRepository`

**Comment by luongvo** [comment]
> Are we going to stick with the `UseCase` naming as well? Just wondering about being descriptive vs being natural to read

I vote to keep the `UseCase` postfix as well. It's more clear and easy to know that task comes from a usecase or it's just a standalone method in ViewModel.

**Comment by sleepylee** [comment]
+1 keep the UseCase name to match with the common naming convention

**Comment by lydiasama** [comment]
I voted to keep the `UseCase` suffix as explained [here](https://github.com/nimblehq/android-templates/discussions/257#discussioncomment-3155104)

**Comment by chornerman** [comment]
+1 keep the `UseCase` suffix

**Comment by suho** [comment]
@nimblehq/android-chapter You guys can check [the naming convention](https://developer.android.com/topic/architecture/domain-layer#conventions) and [invoke function](https://developer.android.com/topic/architecture/domain-layer#use-cases-kotlin) from the domain layer document.

**Comment by sleepylee** [comment]
good eyes, @suho. We were not aware of their updates. Indeed this goes well with what we are currently doing and voting for:
`val todaysDate = formatDateUseCase(today)`

hence, only the `operator fun` is required to be updated from our current implementation
