### ISSUE TITLE
Add version for `new_project.kts` to a properties file

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#264]
## Why

Versioning is useful so that the script can be reported or referenced with the version.

This issue consists of three parts:

**Part 1 : Set-up the properties file**
1. Add `version.properties` to the root folder (if it doesn't already exist)
2. Add a property to indicate the current version of `new_project.kts` → `3.12.0` **(A)** 

**Part 2 : Use the properties file**
When running `new_project.kts`, it must show a message: `"=> Running new project script version **(A)**... 👋" 

**Part 3 : Update documentation**
Update output message with **(A)** when executing `kscript new_project.kts --help`

https://nimble-co.slack.com/archives/G41UCTGHL/p1655106569283399

## Who Benefits?

I think this is **essential** for us developers because it will bring a good experience for us (and others)

**Comment by ryan-conway** [comment]
@Tuubz Would the current version be `1.0.0` or `3.12.0`? 😄

**Comment by Tuubz** [comment]
@ryan-conway Good question 😁 

I guess it makes sense to align the version of the script, with the version of the current milestone 💪 

I've updated the PR description
