### ISSUE TITLE
Add dependency versions for workflows to a properties file

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#265]
## Why

Adding dependency versions to a properties file is good for clarity, and better understanding

This issue consists of three parts

**Part 1 : Set-up the properties file** 
1. Add `version.properties` to the root folder (if it doesn't already exist)
2. Add a property to indicate the Kotlin version used to run `new_project.kts` -> `1.6.21` **(B)**
3. Add a property to indicate the Kscript version used to run `new_project.kts` -> `4.0.3` **(C)**

**Part 2 : Use the properties file**
- When running `verify_newproject_script.yml`, it must make use of **(B)** for the Kotlin version
- When running `verify_newproject_script.yml`, it must make use of **(C)** for the Kscript version
- When running `draft-new-release.yml`, it must make use of **(B)** for the Kotlin version
- When running `draft-new-release.yml`, it must make use of **(C)** for the Kscript version

**Part 3 : Update documentation**
Update `README.md` to specify that **(B)** and **(C)** are required in order to run the script successfully

Reference: https://nimble-co.slack.com/archives/G41UCTGHL/p1655106569283399

## Who Benefits?

I think this is **essential** for us developers because it will bring a good experience for us (and others)

**Comment by luongvo** [comment]
All good 👍
