### ISSUE TITLE
Add unit tests for XML code

### ISSUE THREAD

**Issue by chornerman** [nimblehq/android-templates#298]
## Why

We should consider adding unit tests for the XML code to increase the code coverage
- Add unit tests to the XML template
- Add unit tests to the XML sample

## Who Benefits?

The user of this template

**Comment by Tuubz** [comment]
@chornerman We should add unit tests for `template` & `sample-compose` too, right? 🙏 

I think we'll need to be a bit more specific, the AC is a bit too broad. How much code coverage is enough?

**Comment by chornerman** [comment]
> @chornerman We should add unit tests for `template` & `sample-compose` too, right? 🙏
> 
> I think we'll need to be a bit more specific, the AC is a bit too broad. How much code coverage is enough?

@Tuubz Sorry for the late reply 🙏🏼  About the unit tests for templates, I think we also should add them. Will update this issue accordingly.

**Comment by luongvo** [comment]
@ryan-conway @chornerman Should we prioritize finishing `testing` related tasks? Please re-check to make sure it's still valid for contributing 🙏

**Comment by ryan-conway** [comment]
As we are [deprecating the XML template](https://github.com/nimblehq/android-templates/issues/503), this ticket will no longer be needed 🙇🏻
