### ISSUE TITLE
Upgrade Compile and Target SDK version from 30 to 33

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#300]
## Issue

As Google mentioned in this documentation https://support.google.com/googleplay/android-developer/answer/11926878?hl=en, Android apps should get upgraded on `targetSdkVersion` quite often to adapt to new API changes and Google Play Store conditions for app uploading.

Current supported API level is 30, we should migrate it to 31, 32 (Android 12) or even 33 (Android 13).

## Solution

- Migrate apps to Android 12 https://developer.android.com/about/versions/12/migration
- Migrate apps to Android 13 https://developer.android.com/about/versions/13/migration

## Who Benefits?

Developers

## What's Next?

- [ ] Migrate apps to Android 12 https://developer.android.com/about/versions/12/migration
- [ ] Migrate apps to Android 13 https://developer.android.com/about/versions/13/migration

**Comment by Tuubz** [comment]
@luongvo Could you please close this issue and create a discussion instead?

We will no longer create RFC issues from now on 🙏 

Reference: https://github.com/nimblehq/compass/issues/963

**Comment by lydiasama** [comment]
![Screen Shot 2565-10-03 at 2 10 03 PM](https://user-images.githubusercontent.com/12026942/193519712-5c59b7e4-6574-47fb-8601-419a90e3a771.png)
😂 😂

**Comment by luongvo** [comment]
@Tuubz I just updated the content. This ticket is quite clear and I think we can keep it here without RFC in Discussions. However, I will follow to create RFC later on.
