### ISSUE TITLE
Update Detekt rules for Jetpack Compose

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#303]
## Why

We're still using the legacy Detekt config for Jetpack Compose project, that's why Detekt reports a lot of issues related to new [Jetpack Compose conventions](https://nimblehq.co/compass/development/android/user-interface/jetpack-compose/#conventions). Hence we have to skip them by adding a lot of [`Suppress` annotations as a workaround](https://github.com/nimblehq/jetpack-compose-crypto/blob/develop/app/src/main/java/co/nimblehq/compose/crypto/ui/screens/home/HomeScreen.kt#L34).

There is a [new Detekt rules for Compose](https://detekt.dev/docs/introduction/compose/) should be applied to get rid of those issues.

## Who Benefits?

Developers

**Comment by lydiasama** [comment]
@luongvo Currently, when we create a new project from the script, it generate both `xml` and `compose` project. Does it mean we will not support detekt for the `xml` project after generating it? 🤔 
Also @chornerman  has updated the detekt rules for `sample-compose` project already [here](https://github.com/nimblehq/android-templates/pull/274). So if the consumer could check it in that sample repo.

BTW, do we need to vote on this kind of issue first? @ryan-conway

**Comment by ryan-conway** [comment]
@lydiasama Yes we should vote 😆 Preferably on the [discussions page](https://github.com/nimblehq/android-templates/discussions), but lets migrate slowly 😉 

@luongvo It's true that our Detekt config needs to be updated for Jetpack Compose, but we need to make sure that the new rules we apply don't negatively affect the developer when they choose to use XML instead.
Take function naming for example. We could update the pattern to `[a-zA-Z][a-zA-Z0-9]*` from `[a-z][a-zA-Z0-9]*`, but this means that _all_ functions can be named in Pascal case which is probably not our desired outcome 😉 

Personally I think we should wait for #214 to be implemented and have separate Detekt configs for XML and Compose 🙏🏻

**Comment by luongvo** [comment]
> Also @chornerman has updated the detekt rules for sample-compose project already https://github.com/nimblehq/android-templates/pull/274. So, the consumer could check it in that sample repo.

@lydiasama Yes I see that, however, we're not having full config from https://detekt.dev/docs/introduction/compose. That needs to be updated more 🚀

**Comment by luongvo** [comment]
@ryan-conway Yes, actually we should have different config between legacy XML and Compose projects.
