### ISSUE TITLE
[Type] As a user, I can 

### ISSUE THREAD

**Issue by kingofDaniel** [nimblehq/android-templates#305]
## Why

Describe the idea of the user story as in what the motive of the user story is.

## Acceptance Criteria

List down how the user story will be tested and what criteria are necessary for the user story to be accepted.

## Design

(Optional) Add design screenshots or Figma links for UI/UX-related stories.

## Resources

(Optional) Add useful resources such as links to documentation, implementation ideas, or best practices.

**Comment by ryan-conway** [comment]
Hi @kingofDaniel 👋🏻 

If you would like to report a bug or make any suggestion to the repo, we would recommend to use one the appropriate [issue templates](https://github.com/nimblehq/android-templates/issues/new/choose) for your concern. We typically use [Bug Report](https://github.com/nimblehq/android-templates/issues/new?assignees=&labels=type+%3A+bug&template=bug_template.md&title=Fix%3A+) for bugs and [Request for Comments (RFC)](https://github.com/nimblehq/android-templates/issues/new?assignees=&labels=type+%3A+rfc&template=rfc_template.md&title=RFC%3A+) for other suggestions 😄 

Feel free to update this ticket with details of your concern 👍🏻

**Comment by ryan-conway** [comment]
Closed due to inactivity
