### ISSUE TITLE
Fix: Update readme to match current folder structure

### ISSUE THREAD

**Issue by blyscuit** [nimblehq/android-templates#307]
## Issue

Flowing instruction in `readme` faced error.

<img width="489" alt="Screen Shot 2022-09-13 at 15 02 53" src="https://user-images.githubusercontent.com/6356137/189845773-a38198c8-e840-4c2a-b448-e43d82598086.png">

## Acceptance Criteria

Current `readme` is showing
```
Run kscript new_project.kts to create a new project with the following arguments:
```
while the path to `new_project.kts` is `/scripts/new_project.kts`.

- Include instruction to open the `scripts` folder
or
- Change readme to match the folder.

**Comment by lydiasama** [comment]
@ryan-conway Is this issue fixed by [this PR](https://github.com/nimblehq/android-templates/pull/287)? 🤔

**Comment by ryan-conway** [comment]
@lydiasama Not exactly. That issue fixed a bug that occurred when calling `kscript scripts/new_project.kts`. I think the issue here is that the `readme` says to run `kscript new_project.kts` but does not specify _where_ exactly to run it 🤔

**Comment by lydiasama** [comment]
@ryan-conway I see. I found this issue too when I generated my new app but I think everyone would know that we need to run the script on the script file path. So I didn't create an issue for it. 😅  So I voted this issue +1

**Comment by Tuubz** [comment]
@ryan-conway 

From my understanding, there's no need to specify where exactly to run it 💭 Because when you made [this fix](https://github.com/nimblehq/android-templates/pull/287), it can be run from both root or `/script` folder

**Comment by Tuubz** [comment]
My bad, I misunderstood. It's not possible to run from root 🙏 

To keep it simple, I agree we should just simply update `README.md` to change to `scripts` folder first

**Comment by lydiasama** [comment]
@Tuubz Can I take this one? It seems everyone has their task. 😬

**Comment by Tuubz** [comment]
@lydiasama Yes please, go for it 😊
