### ISSUE TITLE
Update code coverage tool to Kover instead of Jacoco

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#326]
## Why

Jacoco doesn't work correctly when [updating to the latest versions of Gradle & Java](https://github.com/nimblehq/android-templates/pull/323)

[Kover](https://github.com/Kotlin/kotlinx-kover) will not only fix this, but it's also a lot more convenient to set up and to work with (good for the future)

## Who Benefits?

Developers, this is essential to provide a good developer experience

**Comment by AVI5HEK** [comment]
Kover is the new normal.

**Comment by ryan-conway** [comment]
@Tuubz it seems as if Kover has [no support for instrumentation tests](https://github.com/Kotlin/kotlinx-kover/issues/96) right now 🥲 

When a test class is annotated with `@RunWith(AndroidJUnit4::class)`, it will fail to compile. If we remove the annotation, it compiles but the unit tests fail because we need to access the Android framework.

Any ideas? 🤔

**Comment by ryan-conway** [comment]
It doesn't appear to be an issue on @kaungkhantsoe 's [IC](https://github.com/kaungkhantsoe/NimbleSurveyJetpackCompose) though, but that doesn't use Robolectric since all the UI tests are for composables 🤔

**Comment by Tuubz** [comment]
@ryan-conway Would you be able to draft a pull request?

Because TPC also includes Kover with Robolectrics tests, it would be nice to compare for a better understanding 🙏

**Comment by ryan-conway** [comment]
@Tuubz drafted [here](https://github.com/nimblehq/android-templates/pull/344) 🙏🏻

**Comment by Tuubz** [comment]
@ryan-conway Could you try adding this to `build.gradle.kts` ? 🙏 

```
 testOptions {
        ...
        unitTests.all {
            if (it.name != "testStagingDebugUnitTest") {
                it.extensions.configure(kotlinx.kover.api.KoverTaskExtension::class) {
                    isDisabled.set(true)
                }
            }
        }
    }
```

Once we run ` ./gradlew koverMergedHtmlReport` it will execute for all variants, but `EmptyHiltActivity` is only specified in `debug`. Since we only want to execute the tests in debug variant anyways, we can disable kover for `release` 🚀
