### ISSUE TITLE
Rename the current template to XML

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#332]
## Why

The template currently consists of both `XML` & `Compose`.

For the sake of simplicity, we will have a separate template for XML and another one for Compose. 

We rename the current template, so we can still keep track on its git history

## Acceptance Criteria

- Rename `template` to `template-xml`
- Change package name to `co.nimblehq.template.xml`
- Update app name to `Template XML`
- Update the workflows for `template-xml`
- Update `new_project.kts` so it still works correctly

**Note**: Removing the code of Compose will be done in a different issue (#334)

**Comment by luongvo** [comment]
> Create new folder template-xml copied from template
> Change package name to co.nimblehq.template.xml and adjust (AndroidManifest.xml, applicationId, ...)

@Tuubz @Wadeewee  I'm wondering if we follow this way, we will lose all git history from what we contributed into the current `template` folder. Should we rename `template` to the new `template-xml` instead? This way does not actually destroy the history & not require the next task #334 to remove what we just cloned (Compose).

**Comment by Wadeewee** [comment]
Good point @luongvo 👍 So, If we have a plan to remove `template` and use `template-xml` instead I think renaming way it  could be better than copy and remove the previous one then we can keep git history 🤔

**Comment by Tuubz** [comment]
@luongvo @Wadeewee I have updated the issue 🚀 

However, I still believe we should do it in two pull requests (clone first, then remove)

IMO, if we do it in two pull requests it will be clear to see what files of compose are being removed from template-compose.

(Ex: Base classes, dependencies, other gradle configurations, ...)

What do you think? 🙏

**Comment by luongvo** [comment]
@Tuubz lgtm +1
