### ISSUE TITLE
Update `new_project.kts` to choose between XML or Compose

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#336]
## Why

Now the templates have been updated, let's update the script accordingly (= `new_project.kts`)

## Acceptance Criteria

- Add a new flag called `template`, the value can either be `xml` or `compose`
- Ensure a project can be generated correctly for both options
- Ensure the help message is up-to-date
- Update `verify_newproject_script.yml` so the CI still works correctly

**Comment by kaungkhantsoe** [comment]
@Tuubz how should I assign the key name?
1. template=
2. type=
3. template-type=

**Comment by Tuubz** [comment]
@kaungkhantsoe `template` sounds good to me 🚀 

cc @nimblehq/android-chapter

**Comment by luongvo** [comment]
`template` looks good 👍
