### ISSUE TITLE
Migrate workflows setup-ruby action

### ISSUE THREAD

**Issue by Wadeewee** [nimblehq/android-templates#364]
## Why

![Screen Shot 2565-12-08 at 11 15 33](https://user-images.githubusercontent.com/28002315/206366967-01e4f8eb-308d-4110-8750-42801286289b.png)

The `CI` failed on step `Set up Ruby` because the current action is `deprecated` and is `no longer maintained` like above☝️.

## Acceptance Criteria

 Update the action from `actions/setup-ruby@v1` to `ruby/setup-ruby@v1` in files `.github/review_pull_request.yaml` and `.cicdtemplate/review_pull_request.yaml`

Ref: https://github.com/actions/setup-ruby

## Who Benefits?

Android Template

**Comment by Tuubz** [comment]
@Wadeewee Would you agree it's a `bug` instead of `chore`? 🙏

**Comment by Wadeewee** [comment]
@Toby Hmm, It’s migration,  but I’m ok with changing it to a bug instead of a chore
