### ISSUE TITLE
Update Wiki to clarify our voting process in GitHub Discussions

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#378]
## Why

Before, we would apply our voting system directly to the issues (by placing 👍  or 👎 reactions). 

As of now, GitHub Discussions has become a better place for discussing and voting (it supports a built-in poll system)

Also, since we now have separate templates, there's no longer any use for "optional" features 

So, we should update our Wiki accordingly...

## Who Benefits?

The Android team, this update will bring more clarity and a better understanding of how issues are managed

## Acceptance Criteria 

Update the Wiki content:

- Remove everything related to "optional features"

- Clarify the voting process on RFCs (GitHub Discussions): 
   -  RFCs should only be created for chores or features, for bugs we can create an issue directly.
   -  In order to reach a conclusion, at least 50% of the team must cast their vote.
   -  To allow sufficient time for everyone to participate, allow a minimum of one week for voting

- Remove all these labels: `status : essential`, `status : optional`,  `status : rejected` & `status : need voting`

  → Because a feature or chore is already approved/rejected once a discussion has been resolved.

- Issues for bugs can be created without any prior voting.

**Comment by lydiasama** [comment]
> Update naming from "essential" to "approved" in Wiki, also update status : essential label to status: approved

This is a good idea 👍🏻

**Comment by ryan-conway** [comment]
@Tuubz Shall we update the AC on this issue? Since we are going to use RFC discussions for voting, shall we remove the `status : need voting` label? 🤔

**Comment by Tuubz** [comment]
@ryan-conway Yes, definitely, I'll rewrite the AC based on #409 

Thank you 🚀

**Comment by Tuubz** [comment]
@ryan-conway Updated, please let me know if I missed something 🙏

**Comment by lydiasama** [comment]
@ryan-conway @Tuubz For the bug issues created, do we still need this label: `status : need voting` or the maintainer would help reproduce and add the label: `approved` him/herself?

**Comment by Tuubz** [comment]
@lydiasama From my understanding, we will completely remove `status : need voting` & `status : approved` labels.

Once an issue is created, it will automatically be approved already 🙏

**Comment by ryan-conway** [comment]
@lydiasama Since bugs are considered "essential", I don't believe we need to vote on those issues as they should be addressed as soon as possible 🙏🏻

**Comment by lydiasama** [comment]
![Screenshot 2566-03-13 at 10 42 09 AM](https://user-images.githubusercontent.com/12026942/224603166-a76e0f20-70b8-4e3f-9c47-1220e99b66ae.png)

@Tuubz @ryan-conway Got it. So let's add `neet voting` to removed list too. 😬
