### ISSUE TITLE
Update issue templates to automatically included the correct labels

### ISSUE THREAD

**Issue by Tuubz** [nimblehq/android-templates#379]
## Why

Every time I create a new issue, I need to manually add the label for `status : need voting` & `priority : normal`

## Who Benefits?

Repository maintainer, labels are added automatically

## Acceptance Criteria

- The `status : need voting` must be added automatically when creating a new issue (bug, chore, feature, ...)
- The `priority : normal` must be added automatically when creating a new issue (bug, chore, feature, ...)

**Comment by lydiasama** [comment]
> Every time I create a new issue, I need to manually add the label for status : need voting & status : normal

There is one typo here: `priority : normal` 😬

**Comment by Tuubz** [comment]
@lydiasama Sorry, I think I might be blind, what's the typo? 🙈

**Comment by lydiasama** [comment]
> > Every time I create a new issue, I need to manually add the label for status : need voting & status : normal
> 

@Tuubz  There is one typo here: `status : normal` should be `priority : normal` 😬

**Comment by Tuubz** [comment]
@doandinh Thank you for assigning yourself 🥰
