### ISSUE TITLE
[Experiment] Jetpack Compose

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#40]
⚠️ This experiment will not be finished and merged into the main template, just a playground to try a new experiment

## Issue type ✅
- [ ] Bug
- [ ] Feature request
- [x] Improvement request

## The problem 🤔⁉️
Jetpack Compose has been announced by Google at Google I/O 2019.

> Jetpack Compose is an unbundled toolkit designed to simplify UI development. It combines a reactive programming model with the conciseness and ease of use of the Kotlin programming language.

More info could be found at:
- https://android.jlelse.eu/jetpack-compose-android-apps-without-xml-534d74448778
- http://yuyakaido.hatenablog.com/entry/2019/10/14/221955

## Environment, Step to reproduce 💻
TODO

## Further comment, evidence... 🙇🙇
TODO

**Comment by hoangnguyen92dn** [comment]
Close this issue due to created a new [Card](https://github.com/nimblehq/android-templates/projects/3#card-58675751) on Projects.
