### ISSUE TITLE
Add an argument to specify output folder location to `new_project.kts` script

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/android-templates#436]
## Why

[Original RFC](https://github.com/nimblehq/android-templates/discussions/284)

After running the setup scripts, the project folder is created inside the template root folder and all other files are left as is

For example, if we run `kscript new_project.kts package-name=co.nimblehq.suvkmmsurveys.android app-name=Surveys`, 
it may be unclear if `Surveys` or `template` is the right folder 🤔

As such, we should add an argument to the script that accepts an output location where the project should be generated

## Who Benefits?

Android developers

## Acceptance Criteria

- Add an argument `destination` that accepts a path to generated project location
  - If no argument is given, default to template root folder
- `destination` must accept both absolute (`/Users/johndoe/documents/projectfolder`) and relative paths (`../projectfolder`)

**Comment by Tuubz** [comment]
Would `destination` be preferable to `output-folder`? 💭
