### ISSUE TITLE
Migrate Firebase Token to Service Account for Firebase App Distribution

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/android-templates#445]
## Why

[Original RFC](https://github.com/nimblehq/android-templates/discussions/328)

The `FIREBASE_TOKEN` for Firebase App Distribution will soon be deprecated. We should update the template to use a service account instead.

[Migration Guide](https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration)

## Who Benefits?

Android developers

## Acceptance Criteria

- Update Firebase Distribution Github Action to `v1.5.0`
- Update CICD to replace Firebase action `token` with `serviceCredentialsFileContent`
- Add `README.md` in `.cicdtemplate` to show steps how to generate the credentials for usage

**Comment by lydiasama** [comment]
@ryan-conway I think we need to update the specify version for this plugin from `@v1` to `@v1.5.0` too. 🙏🏻

**Comment by luongvo** [comment]
@ryan-conway This ticket is duplicated with https://github.com/nimblehq/android-templates/issues/360. Do you mind closing and replacing one by another 👋

**Comment by ryan-conway** [comment]
Closing as duplicate of #360
