### ISSUE TITLE
Add new sample yaml file for setting up CI/CD with CodeMagic

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/android-templates#448]
## Why

[Original RFC](https://github.com/nimblehq/android-templates/discussions/414)

As of now, we are using [CodeMagic](https://codemagic.io/start/) to execute CI/CD pipelines on some projects, there is a lack of a sample yaml file for quick setup when initializing a new project ([.cicdtemplate](https://github.com/nimblehq/android-templates/tree/develop/.cicdtemplate))

## Solution

- Create a new `.codemagic` folder
- Add new sample yaml file `codemagic.yml` and `README.md` for instruction

## Who Benefits?

Developers

## Acceptance Criteria

- [ ] Create a new `.codemagic` folder
- [ ] Add new sample yaml file `codemagic.yml` and `README.md` for instruction
  - Sample should include running unit tests, detekt and deploying to Firebase App Distribution (similar to `.cicdtemplate/.github/workflows/` folder)

**Comment by lydiasama** [comment]
@ryan-conway Currently, our template does not have the Firebase App Distribution deploy script. So we might skip it on Codemagic too. 🙏

**Comment by ryan-conway** [comment]
@lydiasama There is a Firebase deployment workflow in `.cicdtemplate/.github/workflows/` 😉 I suppose the issue description wasn't too clear, will update it too 😇
