### ISSUE TITLE
Fix: The loading progress continues to display progress even after all parallel tasks have completed

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#458]
## Issue

We had a logic to show and hide the loading progress in `BaseViewModel` automatically. It was made to control showing and hiding the loading progress automatically for parallel tasks, such as parallel API calls at the screen loading time. Unfortunately, the current logic does not work stably, and `it can not hide the loading when two of the tasks are finished at the same time`. 

👉  The loading progress continues to display progress even after all parallel tasks have completed

![screen-20230411-104600 2023-04-11 11_17_41](https://user-images.githubusercontent.com/16315358/231054952-4a35fa04-19fe-4468-bba5-c62b7e4e7740.gif)

- Parallel API calls log
```
I/okhttp.OkHttpClient: --> GET http://192.168.1.122:3001/api/v1/documents/1116/routes
I/okhttp.OkHttpClient: x-mock-response-id: 18834730-2a3b4099-2d46-413e-8316-fe01ceb0c606
I/okhttp.OkHttpClient: DeviceID: 86cdf0440136bf29
I/okhttp.OkHttpClient: Authorization: Bearer xyz
I/okhttp.OkHttpClient: --> END GET
I/okhttp.OkHttpClient: --> GET http://192.168.1.122:3001/api/v1/documents/1116/reason-codes
I/okhttp.OkHttpClient: x-mock-response-id: 18834730-8662fe2e-f6b8-4ffc-bd74-7161062eea0d
I/okhttp.OkHttpClient: DeviceID: 86cdf0440136bf29
I/okhttp.OkHttpClient: Authorization: Bearer xyz
I/okhttp.OkHttpClient: --> END GET
I/okhttp.OkHttpClient: <-- 200 OK http://192.168.1.122:3001/api/v1/documents/1116/routes (1039ms)
I/okhttp.OkHttpClient: Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: Content-Length: 1270
I/okhttp.OkHttpClient: Date: Tue, 11 Apr 2023 04:13:43 GMT
I/okhttp.OkHttpClient: Connection: keep-alive
I/okhttp.OkHttpClient: Keep-Alive: timeout=5
I/okhttp.OkHttpClient: <-- 200 OK http://192.168.1.122:3001/api/v1/documents/1116/reason-codes (1035ms)
I/okhttp.OkHttpClient: Content-Type: application/json; charset=utf-8
I/okhttp.OkHttpClient: Content-Length: 2811
I/okhttp.OkHttpClient: Date: Tue, 11 Apr 2023 04:13:43 GMT
I/okhttp.OkHttpClient: Connection: keep-alive
I/okhttp.OkHttpClient: Keep-Alive: timeout=5
I/okhttp.OkHttpClient: {
I/okhttp.OkHttpClient:   ...
I/okhttp.OkHttpClient: }
I/okhttp.OkHttpClient: <-- END HTTP (1270-byte body)
I/okhttp.OkHttpClient: {
I/okhttp.OkHttpClient:   ...
I/okhttp.OkHttpClient: }
I/okhttp.OkHttpClient: <-- END HTTP (2811-byte body)
```

## Expected

The loading progress should be hidden once all API calls have been completed, regardless of whether they were `successful` or `failed`.

## Steps to reproduce

1. Having a logic in ViewModel with parallel tasks, such as multiple API calls.
2. Binding the loading from `isLoading` StateFlow.
3. Re-check carefully multiple times.

**Comment by ryan-conway** [comment]
Superseded by https://github.com/nimblehq/android-templates/issues/576
