### ISSUE TITLE
Update GitHub workflows to use concurrency

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/android-templates#462]
## Why

The [cancel-workflow action added a warning on their README](https://github.com/styfle/cancel-workflow-action) that GitHub now supports concurrency and this workflow might not be needed anymore.

Resource: https://docs.github.com/en/actions/using-jobs/using-concurrency
Sample implementation: https://github.com/nimblehq/rails-templates/pull/398 

## Acceptance Criteria

- Use concurrency attributes in workflows to ensure only one job is run for each workflow
- Apply update to both `.github` and `.cicdtemplate/.github` workflows
- _Do not_ cancel workflows for deployment jobs:
  - `.github/workflows/publish_docs_to_wiki`
  - `.cicdtemplate/.github/workflows/deploy_staging_and_production_to_firebase_app_distribution.yml`

## Who Benefits?

Developers

**Comment by luongvo** [comment]
Hi @ryan-conway We should push to work on this feature soon. This would help to reduce the action time & billing cost. cc @nimblehq/chapter-android
