### ISSUE TITLE
[Compose] Optimize to test "SharedFlow" execution in Composable with Robolectric

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#465]
## Why

According to the last implementation of [running the Jetpack Compose UI Test with Robolectric](https://github.com/nimblehq/android-templates/pull/399), we have to [switch the `error` from **SharedFlow** to **StateFlow**](https://github.com/nimblehq/android-templates/pull/399/commits/60e64877ad732f5daef82e5bda19320fca75aad2) because we can not make it to be testable with `Robolectric`.

Using `LaunchedEffect` in Jetpack Compose is a standard best practice, and it's hard to find a replacement for `LaunchedEffect`. So in the big picture, if we can not test SharedFlow execution by LaunchedEffect in Composable with Robolectric, we cannot use `Robolectric` as our **main testing framework** for Jetpack Compose to cover all project business logic.

Hence, we should research & find a valid way to [test SharedFlow execution in Composable with Robolectric without converting it to StateFlow](https://github.com/nimblehq/android-templates/pull/399/commits/60e64877ad732f5daef82e5bda19320fca75aad2). This also helps to apply using `viewModel.error.collectAsEffect` for error handling instead of

https://github.com/nimblehq/android-templates/blob/b9304c7ed0b29e2300809babdb19bea3d66e612e/sample-compose/app/src/main/java/co/nimblehq/sample/compose/ui/screens/home/HomeScreen.kt#L38-L39

## Who Benefits?

Developers

**Comment by ryan-conway** [comment]
@luongvo This issue seems very opened ended, I can't see how to define clear acceptance criteria here 🤔 Do you have a concrete suggestion for how to resolve this issue?

**Comment by luongvo** [comment]
> @luongvo This issue seems very opened ended, I can't see how to define clear acceptance criteria here 🤔 Do you have a concrete suggestion for how to resolve this issue?

@ryan-conway It's still an experiment. However, I found a way to resolve it, so clarifying it in the PR is better 🙏
