### ISSUE TITLE
Migrate to Kover 0.7.0

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#470]
## Why

[Kover 0.7.0](https://github.com/Kotlin/kotlinx-kover/releases/tag/v0.7.0) brings many new updates also `breaking changes` that require us to migrate the legacy config to the latest. Please follow this migration guide https://github.com/Kotlin/kotlinx-kover/blob/v0.7.0/docs/gradle-plugin/migrations/migration-to-0.7.0.md for the update.

## Who Benefits?

Developers

**Comment by kaungkhantsoe** [comment]
Hello @luongvo, for this issue, I agree with you on `breaking changes`. I tried the new version and there are a lot of major changes. I think it is best for the team to be able to use the latest version of Kover. But I don't see any discussion about this. Shall we create one?

**Comment by luongvo** [comment]
@kaungkhantsoe Discussion about whether we should migrate to the new version or which else, please? IMHO, it's not something `new`, and the new version is always good to upgrade to applying the new features or bug fixes. What do you think?

**Comment by kaungkhantsoe** [comment]
@luongvo I agree with you. I am just asking because you added `need voting` tag 😁. I also think we should upgrade the version without voting since it will only bring good for us. 👍

**Comment by luongvo** [comment]
@kaungkhantsoe I did not add that label tbh 🥲 it came from [this effort](https://github.com/nimblehq/android-templates/pull/404) to automatically add that label on new submissions. I think the repo's maintainer @ryan-conway should take care of the voting process here, and decide whether should we create an RFC or approve to add any into an Iteration if it's simple and clear enough (aka remove that label) cc @nimblehq/android-chapter
