### ISSUE TITLE
Deprecate the XML template 

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/android-templates#503]
## Why

As we move towards Jetpack Compose and away from XML when creating new projects, we should deprecate the XML template and provide only limited support, such as dependency upgrades or critical bug fixes

## Who Benefits?

Developers

## Acceptance Criteria

- Create new `deprecated` folder in root directory
- Move `RxJavaTemplate`, `template-xml` and `sample-xml` into the new folder
- Remove references to the XML template from all workflows

**Comment by luongvo** [comment]
@ryan-conway Moving all deprecated templates into a new folder, such as `deprecated`/`.deprecated`, could be better to focus on the existing template IMO 🤔 cc @nimblehq/chapter-android
