### ISSUE TITLE
Add asStateFlow to the StateFlow variables in ViewModel class

### ISSUE THREAD

**Issue by ryan-conway** [nimblehq/android-templates#535]
[Original RFC](https://github.com/nimblehq/android-templates/discussions/518)

## Why

Currently we can emit values to our `StateFlow` variables by casting them to `MutableStateFlow`. We should update our `StateFlow` declarations to make them read-only

## Solution

- Update our `StateFlow` declarations as follows:
  ```
  private val _uiModels = MutableStateFlow<List<UiModel>>(emptyList())
  val uiModels = _uiModels.asStateFlow()
  ```
- Apply updates to `template-compose` and `sample-compose` ViewModels

## Who Benefits?

Developers

**Comment by luongvo** [comment]
@kaungkhantsoe please update your ticket status. Currently, it's in Icebox.
