### ISSUE TITLE
Add basic test components to CoroutinesTemplate

### ISSUE THREAD

**Issue by hoangnguyen92dn** [nimblehq/android-templates#85]
## Why

Add basic test components to CoroutinesTemplate

:white_check_mark: **Acceptance Criteria**
- [ ] Add testing libraries
- [ ] Add basic test functions

**Comment by doannimble** [comment]
This issue should start right after closing https://github.com/nimblehq/android-templates/issues/131

**Comment by Tuubz** [comment]
@hoangnguyen92dn @doannimble 

I'm a bit unsure what's the expectation, based on the acceptance criteria 🙏 

>  Add testing libraries

Testing libraries are already included in `CoroutineTemplate` -> `mockk`, `kotest`, `robolectric`, ... 

> Add basic test functions

I think we should be more specific here on what's the goal, it sounds very broad 🙇

**Comment by Tuubz** [comment]
@hoangnguyen92dn 

I think we can close this one, what do you think? 🙏

**Comment by hoangnguyen92dn** [comment]
@Tuubz Yup 👍 Since @manh-t added UnitTest in CoroutineTemplate so we could close this 🚀
